name: Release Process
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  lock-main-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Lock main branch
        run: |
          chmod +x ./.github/scripts/lock-unlock-main-branch.sh
          ./.github/scripts/lock-unlock-main-branch.sh true
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_REPONAME: ${{ github.event.repository.name }}
          MAIN_BRANCH: "main"
          REPO_OWNER: "brajagopal-zettle"
  fetch-branch-protection-settings:
    needs: lock-main-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Get branch protection
        run : |
          branch_protection=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO_OWNER/$PROJECT_REPONAME/branches/$MAIN_BRANCH/protection")
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_REPONAME: ${{ github.event.repository.name }}
          MAIN_BRANCH: "main"
          REPO_OWNER: "brajagopal-zettle"
      - name: Extract lock_branch.enabled
        run: |
          # Extract the `lock_branch.enabled` field from the branch protection output
          lock_branch_enabled=$(echo "$branch_protection" | jq -r '.lock_branch.enabled')
      - name: Set lock_branch_enabled output
        run: |
          # Set the lock_branch_enabled output for use in the next job
          echo "::set-output name=lock_branch_enabled::$lock_branch_enabled"
  create-issue-for-release:
    needs: fetch-branch-protection-settings
    runs-on: ubuntu-latest
    if: ${{ needs.fetch-branch-protection-settings.outputs.lock_branch_enabled == 'true' }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Run create issue script
        run: |
          chmod +x ./.github/scripts/create-issue.sh
          ./.github/scripts/create-issue.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_REPONAME: ${{ github.event.repository.name }}
          MAIN_BRANCH: "main"
          REPO_OWNER: "brajagopal-zettle"