name: Release Process
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  lock-main-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Lock main branch
        run: |
          chmod +x ./.github/scripts/lock-unlock-main-branch.sh
          ./.github/scripts/lock-unlock-main-branch.sh true
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          PROJECT_REPONAME: ${{ github.event.repository.name }}
          MAIN_BRANCH: "main"
          REPO_OWNER: "brajagopal-zettle"
  fetch-branch-protection-settings:
    needs: lock-main-branch
    runs-on: ubuntu-latest
    outputs:
      lock_branch_enabled: ${{ steps.set-lock-branch-enabled.outputs.lock_branch_enabled }}
    steps:
      - id: set-lock-branch-enabled
        name: Get branch protection
        run : |
          branch_protection=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO_OWNER/$PROJECT_REPONAME/branches/$MAIN_BRANCH/protection")
          echo "branch_protection : $branch_protection"
          lock_branch_enabled=$(echo "$branch_protection" | jq -r '.lock_branch.enabled')
          echo "lock_branch_enabled: $lock_branch_enabled"
          echo "lock_branch_enabled=$lock_branch_enabled" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          PROJECT_REPONAME: ${{ github.event.repository.name }}
          MAIN_BRANCH: "main"
          REPO_OWNER: "brajagopal-zettle"
  create-issue-for-release:
    needs: fetch-branch-protection-settings
    runs-on: ubuntu-latest
    if: ${{ needs.fetch-branch-protection-settings.outputs.lock_branch_enabled == 'true' }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Run create issue script
        run: |
          chmod +x ./.github/scripts/create-issue.sh
          ./.github/scripts/create-issue.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          PROJECT_REPONAME: ${{ github.event.repository.name }}
          MAIN_BRANCH: "main"
          REPO_OWNER: "brajagopal-zettle"