name: Release Process
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  lock-main-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Lock main branch
        run: |
          chmod +x ./.github/scripts/lock-unlock-main-branch.sh
          ./.github/scripts/lock-unlock-main-branch.sh true
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PROJECT_REPONAME: ${{ github.event.repository.name }}
          MAIN_BRANCH: "main"
          REPO_OWNER: "brajagopal-zettle"
  create-issue-for-release:

    runs-on: ubuntu-latest
    if: ${{ needs.lock-main-branch.result == 'success' }}
    needs: lock-main-branch
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Run create issue script
        run: |
          chmod +x ./.github/scripts/create-issue.sh
          ./.github/scripts/create-issue.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PROJECT_REPONAME: ${{ github.event.repository.name }}
          MAIN_BRANCH: "main"
          REPO_OWNER: "brajagopal-zettle"